
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb

    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 30s
      timeout: 30s
      retries: 3
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"  # MQTT default port
      - "8080:8080"  # Websocket port (optional)
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    environment:
      - TZ=UTC  # Set your timezone if needed
volumes:
  mongodb_data:  
  mosquitto: