version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb

    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  mongodb_data: