[project]
name = "backend"
version = "0.1.0"
description = "Backend API with FastAPI"
dependencies = [
    "fastapi",
    "uvicorn"
]
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
